# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update_description_files:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install curl libxml2-utils python3-requests

    - uses: actions/checkout@v4
    
    - name: Pull UE description files
      env:
        DROPSU_USER: ${{ secrets.DROPSU_USER }}
        DROPSU_PASS: ${{ secrets.DROPSU_PASS }}
        DROPSU_FOLDER: ${{ vars.DROPSU_FOLDER }}
        DROPSU_ENDPOINT: ${{ vars.DROPSU_ENDPOINT }}
      run: |
        ./fetch
        ls -la . figures
      
    # Auto-commit changed files
    - name: Auto-commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Mise à jour des fiches d'UE"
        commit_user: ${{ github.actor }}
